Repository suurt8ll/open_webui_functions, pull requests merged in 2025-05, with the labels that each got.

#100 feat: native PDF support
  examples/bypass_files_processing.py
  plugins/filters/gemini_manifold_companion.py
  plugins/pipes/gemini_manifold.py
  utils/manifold_types.py
Labels: enhancement, P1

#87 feat(gemini): add support for Google Cloud Vertex AI integration
  plugins/pipes/gemini_manifold.py
Labels: enhancement

#144 fix(gemini): Vertex AI does not support URL context.
  plugins/pipes/gemini_manifold.py
Labels: bug, P1, gemini_manifold
